isaacHagoel/svelte-dnd-action

README.md
package.json
src/action.js
src/helpers/styler.js

63 disable dz

---

package.json
src/helpers/styler.js

78 - toggling user select when dragDisabled changes

---

package.json
src/helpers/styler.js

bumped up the version and added info to JSDoc

---

package.json
src/helpers/windowScroller.js

70 - added touch support to windowScroller.js

---

package.json
src/action.js

77 element removal timing

---

README.md
cypress/integration/util.spec.js
package.json
src/action.js
src/helpers/styler.js
src/helpers/util.js

111 drop target style realtime update

---

package.json
src/action.js

108 - ignoring any non left button mouse click. 

---

package.json
yarn.lock

removed all of the un-needed deps and dev deps, reducing the unpacked size by more than 2/3
resolves #18

18 - removed all of the un-needed deps and dev deps

---

README.md
package.json

110 - added links to REPLs with examples

---

cypress/integration/dispatcher.spec.js

115 - fixed the tests. resolves #115

---

README.md
package.json

119 badges in readme

---

README.md
package.json
src/action.js
src/index.js

90 - added an ability to globally override the id key

---

package.json
src/action.js

68 - added checks on missing items or missing id key

---

README.md
package.json

125 - removed broken badge from README.md

---

package.json
src/helpers/styler.js

127 - copying styles from the original element when creating the dragged element

---

package.json
src/pointerAction.js

135 - maintaining focus on drag start

---

package.json
src/pointerAction.js

removed caching of shadowElIdx, this allows a consider/finalize event handler to sort the list however they like without breaking.
resolves #131

131 - removed caching of shadowElIdx

---

README.md
package.json
src/constants.js
src/keyboardAction.js

144 - added a new trigger "dragStopped". dispatching it from the keyb…oard action when appropriate.

---

README.md
package.json

139 - added a new example for unsortable lists and custom aria instructions

---

README.md
package.json

140 - added an example for custom styling of the shadow element

---

package.json
src/helpers/styler.js

154 - copying list-style-type to dragged element. mainly useful for "none"

---

package.json
src/constants.js
src/helpers/aria.js
src/keyboardAction.js

159 - made the library SSR friendly again and paid some tech debt

---

.eslintrc.js
package.json
src/action.js
src/helpers/util.js
src/pointerAction.js
yarn.lock

19 - added eslint and made minor changes based on its output

---

README.md
package.json
rollup.config.js
src/action.js
typings/index.d.ts
yarn.lock

143 - exporting type definitions and fixed a small issue from the introduction of eslint

---

package.json
src/keyboardAction.js

166 - not starting drag when space/enter is pressed on a nested input element

---

README.md
package.json
src/keyboardAction.js

169 - made it so any nested element will not be focusable. allowing clicking on nested elements to start dragging them

---

package.json
src/keyboardAction.js

172 - ignoring contenteditable children for enter and spacebar

---

README.md
cypress/integration/util.spec.js
src/constants.js
src/helpers/observer.js
src/helpers/windowScroller.js
src/index.js
src/keyboardAction.js
src/pointerAction.js
typings/index.d.ts

closes #165 
* Not sure if you want to have this in `constants.js`, but I thought this is not enough code to create its own file. Let me know what you think about this.
* Also my editor fixed a lot of inconsistent code formatting (indentations, semicolons, single/double quotes, et.). Let me know if this is okay for you, or if you want me to remove it from the PR or move to a second PR for clarity.
* A test for the debug function would be a good idea, but I'm not sure if there's a way to assert console output via Cypress.

feat: make debug output configurable

---

package.json
src/keyboardAction.js
yarn.lock

if a dndzone is removed mid drag it is treated as a drop (when keyboard dragging). 
upgraded all dependencies (unrelated)
fixed #191

191 - if a dndzone is removed mid drag it is treated as a drop (when keyboard dragging)

---

README.md
package.json

Generic list example

---

package.json
src/helpers/styler.js

130 - copying all styles from the children in order to prevent glitches in the styling of the dragged element

---

package.json
src/helpers/aria.js

194 init aria only after dom content loaded

---

README.md
package.json

182 - added an example to README.md

---

package.json
src/helpers/styler.js

199 - reverted recursive copying of styles

---

package.json
src/pointerAction.js

204 - ignoring mouse downs on input elements

---

README.md
package.json
release-notes.md

215 - fixed release notes and README.md (the example itself was fixed in the REPL)

---

package.json
release-notes.md
src/keyboardAction.js

225 - managing the tab index of the dragged element to allow tabbing back to it even after tabbing to external elements

---

README.md
package.json
typings/index.d.ts

228 - fixed setDebugMode documentation and typescript info

---

package.json
release-notes.md
src/helpers/dispatcher.js
src/helpers/observer.js
src/pointerAction.js

230 - added handling for dragged entered another dropzone on which drop from others is disabled

---

package.json
src/pointerAction.js

233 - moved the state change to below the condition

---

README.md
package.json

236 server example

---

README.md
package.json
release-notes.md
src/index.js
typings/index.d.ts

243 - exposed SHADOW_PLACEHOLDER_ITEM_ID

---

README.md
package.json

285 - readme improvements (two new examples and some clarifications)

---

package.json
release-notes.md
src/pointerAction.js

289 - fix for disabling drop from others when the shadow element is in a zone

---

src/pointerAction.js

Fixes https://github.com/isaacHagoel/svelte-dnd-action/issues/300

300 - ensure children styles don't break with customElements

---

README.md
package.json
release-notes.md

318 - added a link example for a basic implementation of multi-drag in the README

---

package.json
release-notes.md
typings/index.d.ts

330 - fixed the typescript type for dropTargetClasses

---

package.json
release-notes.md
src/helpers/listUtil.js
src/helpers/observer.js
src/helpers/windowScroller.js

312 - resetting the shadow rect cache for a zone that autoscrolled and the window autoscrolls

---

src/helpers/styler.js
src/helpers/svelteNodeClone.js

306: set selected options to node clone

---

README.md
package.json
release-notes.md
typings/index.d.ts

Should be backwards compatible.

Made DndEvent generic, falling back to Item

---

README.md
package.json
release-notes.md

chore: examples not working, bumps up svelte version

---

README.md
package.json
release-notes.md

based on https://github.com/isaacHagoel/svelte-dnd-action/issues/445#issuecomment-1612118075
fixes #445

445 - updated the readme to deal with svelte 4 eslint

---

README.md

Hi, `setFeatueFlag` should be renamed to `setFeatureFlag` (with an R)
Just spent an hour trying to figure out why my code was throwing an error. :'(

Spelling setFeatureFlag

---

README.md
package.json
release-notes.md
src/action.js
src/constants.js
src/pointerAction.js
typings/index.d.ts

This is currently the most evolved and leading candidate for simplifying and controlling nested zones throughout the drag.
fixes #483

483c disallowing nested shadows and using the placeholder throughout drag

---

package.json
release-notes.md
src/helpers/svelteNodeClone.js

fixed node clone not working with canvas　

---

package.json
release-notes.md
src/helpers/svelteNodeClone.js

523 - added "exports" for svelte 5, the rest is formatting changes

---

package.json
release-notes.md

526 - fixed the export

---

package.json
release-notes.md
src/pointerAction.js

512 - not copying dragged item in order to support class instances

---

README.md
package.json
release-notes.md
src/pointerAction.js

531 - better fault tolerance when the shadow element is absent

---

package.json
release-notes.md
src/pointerAction.js

570 - calling transformDraggedElement after the element was morphed so that changes it makes aren't overridden

---

README.md
package.json
release-notes.md
src/index.js
src/wrappers/simpleStore.js
src/wrappers/withDragHandles.js
typings/index.d.ts

509 - added two new wrapper actions to make it easy to use drag handles

---

package.json
release-notes.md
src/helpers/multiScroller.js
src/helpers/scroller.js
src/pointerAction.js

564 - destroying the scroller on drop

---

package.json
release-notes.md
src/helpers/svelteNodeClone.js

Otherwise will throw an error, see: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#exceptions

fix: fix issue with empty canvas

---

package.json
release-notes.md
src/helpers/intersection.js
src/pointerAction.js

609 - added a recursive bounding rect function that removes parts of the bounding rect that are hidden inside a higher level scroll container

---

package.json
release-notes.md
src/pointerAction.js

changed the logic of the shadow element retrieval when un-decorating it on drop

---

package.json
release-notes.md
src/pointerAction.js

checking if the dndzone is inside popover element

---

README.md
package.json
release-notes.md

updated readme wrt Svelte 5 event handlers

---

package.json
release-notes.md
src/pointerAction.js

637 - added a fix for a svelte 5 race condition that was introduced by the previous version

---

package.json
release-notes.md
src/wrappers/withDragHandles.js

bugfix - now dragDisabled is respected by the draghandle

---

README.md
package.json
release-notes.md
src/action.js
src/pointerAction.js
typings/index.d.ts

added delay on touch start

---

package.json
release-notes.md
src/helpers/listUtil.js
src/pointerAction.js

Fixes #656 
See https://github.com/isaacHagoel/svelte-dnd-action/issues/656#issuecomment-3091765179

Change the handling around deciding whether the would be index should be at the end of the list
