isaacHagoel/svelte-dnd-action

package.json
src/action.js
src/helpers/styler.js

We keep the original element in the dom so we don't interrupt the flow of touch events and remove it when drag ends
fixes #58

58 - added an ugly workaround that fixes the issue. 

---

README.md
src/action.js
src/helpers/styler.js

Add dropTargetStyle

---

package.json
rollup.config.js
src/action.js
src/helpers/aria.js
src/helpers/styler.js
src/pointerAction.js
yarn.lock

added rollup + babel so that consumers don't need to worry about transpiling the code. removed direct references to svelte in ids. fixed a small bug that affected the dragula example (unrelated)
resolves #129

129 - added rollup + babel

---

package.json
src/helpers/intersection.js

fixed the issue. now dragging the one before last element works as expected. added a function that removes the transforms when calculating the would be index

150 - ignore transforms when calculating would-be index

---

package.json
src/helpers/styler.js
src/keyboardAction.js

152 - fixed the typo "keyDown" instead of "keydown" that was causing the issue. unrelated: removed un-needed name attribute

---

src/helpers/styler.js

This fixes some bugs I've experienced while dragging items in Safari.
Edit: I should have mentioned that Safari needing the "webkit" prefix on this property in Javascript is [documented here](https://www.w3schools.com/jsref/prop_style_userselect.asp).

Include Safari's webkitUserSelect

---

.gitignore
package.json
src/constants.js
src/helpers/intersection.js
src/helpers/listUtil.js
src/helpers/observer.js
src/helpers/styler.js
src/pointerAction.js

added caching for the position of the shadow element in given indexes, which gets reset after every drag operation. this allows to not "get confused" by large element that shouldn't move out of the way.
fixes #188

188 dragging small over large

---

README.md
package.json
release-notes.md
src/constants.js
src/helpers/dispatcher.js
src/helpers/observer.js
src/helpers/styler.js
src/pointerAction.js
typings/index.d.ts

basic implementation. incomplete (see TODO items). makes the placeholder appear in the origin zone when it is outside of any. not optional
resolves #201

201 - placeholder in origin zone when dragged outside of any and origin zone min dimensions control

---

package.json
src/helpers/intersection.js
src/pointerAction.js

removing transform when getting the rect for the final animation so that the element always animates to the correct place (not misled by ongoing flips)
fixes #208

208 - removing transform when getting the rect for the final animation

---

package.json
release-notes.md
src/constants.js
src/pointerAction.js

keeping a shadow item with a temporary id on drag start, removing on drag entered. this prevents the list from having a missing item, even for an instant and also removes ambiguity about the initial would be index
resolves #211

211 - keeping a shadow item with a temporary id on drag start

---

package.json
release-notes.md
src/keyboardAction.js

219 - added dropTargetClasses to keyboard config

---

README.md

Fix PR fixes a typo that will cause errors when copying the Typescript code snippet.

Fix typo in Typescript instruction snippet

---

src/keyboardAction.js

**Before**
Notice, how, even though the button is focused, I can't press it with spacebar. Doing so initiates drag mode.
**After**
After the change, I can press fire buttons with spacebar. And I can also initiate drag mode by selecting the containing element.

Allow child buttons to be pressed with keyboard

---

package.json
release-notes.md
src/helpers/styler.js
src/pointerAction.js

362 - fix: if a dropzone is destroyed during drag, it is kept in the DOM (hidden) until a drop takes place to prevent mid drag errors

---

README.md
package.json
release-notes.md
src/action.js
src/constants.js
src/featureFlags.js
src/helpers/styler.js
src/helpers/svelteNodeClone.js
src/index.js
typings/index.d.ts

fixes #470 
also affects #454  - will now need to use the flag to enable that workaround

470 feature flag for grid workaround

---

package.json
release-notes.md
src/pointerAction.js

Hey, this is linked to Issue #479 (second try)
This solution seems to be working fine.
When rewatching the dragged element the config of the new zone has to be read, so the `registerDropZone` method has to fire after the config added to the config map.

Rewatch dragged element on zone registration while dragging

---

package.json
release-notes.md

The package types were not able to be resolved with the new `exports` field being added. This PR fixes that by defining the `import` and `require` properties in `exports`.
References:
- https://nodejs.org/api/packages.html#package-entry-points
- https://nodejs.org/api/packages.html#conditional-exports
Side note: I'm not sure why the `svelte` property is targeting `src/index.js` rather than `dist/index.js`. I tested using `dist` locally and my SvelteKit project compiled and ran without issues.

fix: add import and require exports

---

README.md
package.json
release-notes.md

Hi there! I'm using this library with SvelteKit and ran into some issues after I followed the instructions in the README to set up types for the events. The language server started complaining that it could not find type declarations for things like `./$types` or `$lib/....`. It turns out that the Typescript does not allow "extending" of the `include` key and adding an `include` element at the root `tsconfig.json` resulted in the ts compiler not knowing about the types that sveltekit declares. Thankfully this is easily solved by using sveltekit's function to modify the generated config rather than editing the root config. 
I just threw this in the readme for now, but happy to move it to where ever you feel is more appropriate.

docs: update README to help sveltekit + TS users

---

README.md
package.json
release-notes.md
typings/index.d.ts

I have added types for action `dndzone` custom events `on:consider` and `on:finalize`, which will prevent type errors and infer the type of the events properly when using TypeScript.

Improve custom events typing

---

package.json
release-notes.md

When using svelte 5.0.0-next, svelte-dnd-action causes a peer dependency issue. Since svelte-dnd-action appears to be compatible with svelte 5, it would be helpful to allow svelte 5.0.0-next as peer dependency.

Allow svelte ^5.0.0-next.0 as peer dependency

---

README.md
package.json
release-notes.md

577 - Added examples for drag handles via wrapper actions to the README

---

package.json
release-notes.md
src/pointerAction.js

When rapidly moving items around within a single list, there were cases `multiScroller` was undefined when accessed (`destroy()` called) and caused an unhandled exception that left the `dndzone` in an unusable state until refresh. 
The solution I found was to wrap `multiScroller` in a truthy if block before attempting to destroy and set undefined. The check could be made safer by also ensuring `destroy` is a function on the `multiScroller` object, but that's probably overkill for this case.

multiScroller undefined on destroy

---

README.md
release-notes.md

The title says it all.
`https://svelte.dev/repl/...`
now is
`https://svelte.dev/playground/...`

Change outdated /repl/ urls to /playground/

---

package.json
release-notes.md
src/pointerAction.js

635 - separated the adding of the dragged element to the dom from keeping the original to prevent morph from running before it's in the DOM

---

package.json
release-notes.md
src/wrappers/withDragHandles.js

**Problem**: When clicking and releasing the drag handle without dragging, `isItemsDragDisabled` remains `false`, causing the entire element (and all others) to become draggable instead of only by the handle. I believe this is an unintended side effect that degrades the drag handle functionality.
**Solution**: Added `mouseup` and `touchend` event listeners in `dragHandle` to reset `isItemsDragDisabled` to `true` if no drag is initiated. The listeners are cleaned up properly.
**Testing**: I have tested this fix in a Svelte 5 project with both mouse and touch inputs, and it resolves the issue without introducing new problems. However, I have not conducted exhaustive testing across all use cases. Please let me know if you'd prefer this to be reported as an issue first or if further testing …

Fix dragHandle bug: Reset isItemsDragDisabled on click without drag
